## Below is the starter code

In [ ]:
import pandas as pd

data = {
"Name": [
    "Alice", "Bob", "Charlie", "David", "Evelyn",
    "Frank", "Grace", "Henry", "Isla", "Jack",
    "Karen", "Leo", "Mia", "Noah", "Olivia",
    "Paul", "Quinn", "Ruby", "Sam", "Tina"
],
"Age": [25, 32, 37, 29, 41, 28, 34, 45, 26, 31, 39, 27, 33, 36, 30, 42, 24, 38, 35, 29],
"Department": [
    "HR", "Engineering", "Sales", "Marketing", "Engineering",
    "Finance", "Support", "Operations", "HR", "Sales",
    "Engineering", "Support", "Marketing", "Finance", "Operations",
    "Engineering", "HR", "Sales", "Support", "Marketing"
],
"Salary": [
    50000, 75000, 62000, 58000, 80000,
    54000, 52000, 70000, 51000, 64000,
    82000, 53000, 60000, 56000, 68000,
    79000, 49500, 65500, 54500, 61000
],
}

df = pd.DataFrame(data)

## Exercise Set 1:Exercise 1

In [ ]:
print(df.head())

      Name  Age   Department  Salary
0    Alice   25           HR   50000
1      Bob   32  Engineering   75000
2  Charlie   37        Sales   62000
3    David   29    Marketing   58000
4   Evelyn   41  Engineering   80000

## Exercise Set 1:Exercise 2

In [ ]:
print(df.tail())

     Name  Age   Department  Salary
15   Paul   42  Engineering   79000
16  Quinn   24           HR   49500
17   Ruby   38        Sales   65500
18    Sam   35      Support   54500
19   Tina   29    Marketing   61000

## Exercise Set 1:Exercise 3

In [ ]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        20 non-null     str
 1   Age         20 non-null     int64
 2   Department  20 non-null     str
 3   Salary      20 non-null     int64
dtypes: int64(2), str(2)
memory usage: 772.0 bytes
None

## Exercise Set 1:Exercise 4

In [ ]:
print(df.shape)

(20, 4)

## Exercise Set 2

In [26]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

## Exercise Set 2: Exercise 1

In [9]:
print(df.loc[12,['Name','Age']])

Name    Saundercock, Mr. William Henry
Age                               20.0
Name: 12, dtype: object

## Exercise Set 2: Exercise 2

In [13]:
print(df.iloc[0:5,0:3])

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

## Exercise Set 2: Exercise 3

In [34]:
print(df.loc[df['Pclass'] == 1 & (df['Sex'] == 'female')])

     PassengerId  Survived  Pclass  \
1              2         1       1
3              4         1       1
11            12         1       1
31            32         1       1
52            53         1       1
..           ...       ...     ...
856          857         1       1
862          863         1       1
871          872         1       1
879          880         1       1
887          888         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
11                            Bonnell, Miss. Elizabeth  female  58.0      0
31      Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN      1
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.0      1
..                                                 ...     ...   ...    ...
856         Wick, Mrs. George Dennick (Mary Hitchcock)  female  45.0      1
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  female  48.0      0
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0

     Parch    Ticket      Fare Cabin Embarked
1        0  PC 17599   71.2833   C85        C
3        0    113803   53.1000  C123        S
11       0    113783   26.5500  C103        S
31       0  PC 17569  146.5208   B78        C
52       0  PC 17572   76.7292   D33        C
..     ...       ...       ...   ...      ...
856      1     36928  164.8667   NaN        S
862      0     17466   25.9292   D17        S
871      1     11751   52.5542   D35        S
879      1     11767   83.1583   C50        C
887      0    112053   30.0000   B42        S

[94 rows x 12 columns]

## Exercise Set 2: Exercise 4

In [31]:
print(df.iloc[9]['Age'])

14.0

## Exercise Set 2: Exercise 5

In [32]:
print(df.loc[100:105,['Fare','Survived']])

        Fare  Survived
100   7.8958         0
101   7.8958         0
102  77.2875         0
103   8.6542         0
104   7.9250         0
105   7.8958         0

## Exercise Set 3: Exercise 1

In [33]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [35]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## Exercise Set 3: Exercise 2

In [47]:
print(df['Embarked'].value_counts())

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

## Exercise Set 3: Exercise 4

In [54]:
print(df['Pclass'].value_counts())

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

## Exercise Set 3: Exercise 4

In [55]:
print(df['Age'].mean())

29.69911764705882

## Exercise Set 3: Exercise 5

In [56]:
print(df['Fare'].max())

512.3292

## Exercise Set 3: Exercise 6

In [57]:
print(df['Name'].nunique())

891

## Exercise Set 3: Exercise 7

In [58]:
print(df['Sex'].value_counts())

Sex
male      577
female    314
Name: count, dtype: int64

## Exercise Set 3: Exercise 8

In [59]:
print(df.nunique())

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

## Section 2: Exercise 1

In [76]:
import pandas as pd
# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['NYC', 'LA', 'Chicago', 'Miami'],
    'Email': ['a@example.com', 'b@example.com', 'c@example.com', 'd@example.com']
}
df = pd.DataFrame(data)

In [63]:
df_no_email = df.drop('Email', axis=1)
print(df_no_email)

      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago
3    David   40    Miami

## Section 2: Exercise 2

In [70]:
df.drop(df.index[2], inplace=True)
print(df)

    Name  Age   City          Email
0  Alice   25    NYC  a@example.com
1    Bob   30     LA  b@example.com
3  David   40  Miami  d@example.com

## Section 2: Exercise 3

In [74]:
df = df.drop(['Email', 'City'], axis=1)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [77]:
df_trimmed = df.drop([0, 3], axis=0)
print(df_trimmed)

      Name  Age     City          Email
1      Bob   30       LA  b@example.com
2  Charlie   35  Chicago  c@example.com

## Exercise Set 2: Missing Data

In [87]:
import pandas as pd
import numpy as np

data = {
"Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
"Age": [25, np.nan, 35, 40, None],
"City": ["NYC", "LA", None, "Miami", "Boston"],
}

df = pd.DataFrame(data)

## Exercise Set 2: Exercise 1

In [79]:
print(df.head())

      Name   Age    City
0    Alice  25.0     NYC
1      Bob   NaN      LA
2  Charlie  35.0     NaN
3    David  40.0   Miami
4      Eva   NaN  Boston

## Exercise Set 2: Exercise 2

In [80]:
df.isnull()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

## Exercise Set 2: Exercise 3

In [81]:
df.isnull().sum()

Name    0
Age     2
City    1
dtype: int64

## Exercise Set 2: Exercise 4

In [84]:
print(df.dropna())

    Name   Age   City
0  Alice  25.0    NYC
3  David  40.0  Miami

## Exercise Set 2: Exercise 6

In [86]:
print(df.dropna(axis=1))

      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eva

## Exercise Set 2: Exercise 8

In [88]:
df.fillna(df['Age'].mean())
print(df)

      Name   Age    City
0    Alice  25.0     NYC
1      Bob   NaN      LA
2  Charlie  35.0     NaN
3    David  40.0   Miami
4      Eva   NaN  Boston

## Exercise Set 2: Exercise 9

In [91]:
df['City'] = df['City'].fillna('Unknown')     
print(df)

      Name   Age     City
0    Alice  25.0      NYC
1      Bob   NaN       LA
2  Charlie  35.0  Unknown
3    David  40.0    Miami
4      Eva   NaN   Boston

## Exercise Set 3: Duplicates

In [92]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Diana"],
"Age": [25, 30, 35, 25, 30, 40],
"City": ["NYC", "LA", "SF", "NYC", "LA", "NYC"],
}

df = pd.DataFrame(data)

## Exercise Set 3: Exercise 1

In [95]:
print("\nDuplicated rows (True if row is a duplicate of an earlier one):")
print(df.duplicated())

Duplicated rows (True if row is a duplicate of an earlier one):
0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

## Exercise Set 3: Exercise 2

In [96]:
print("\nDataFrame with duplicates dropped (keep='first'):")
print(df.drop_duplicates(keep='first'))

DataFrame with duplicates dropped (keep='first'):
      Name  Age City
0    Alice   25  NYC
1      Bob   30   LA
2  Charlie   35   SF
5    Diana   40  NYC

## Exercise Set 3: Exercise 3

In [97]:
print("\nDataFrame with duplicates dropped (keep='last'):")
print(df.drop_duplicates(keep='last'))

DataFrame with duplicates dropped (keep='last'):
      Name  Age City
2  Charlie   35   SF
3    Alice   25  NYC
4      Bob   30   LA
5    Diana   40  NYC

## Exercise Set 3: Exercise 4

In [98]:
print("\nDataFrame with ALL duplicates removed (keep=False):")
print(df.drop_duplicates(keep=False))

DataFrame with ALL duplicates removed (keep=False):
      Name  Age City
2  Charlie   35   SF
5    Diana   40  NYC

## Section 3: Data Wrangling Essentials

## Exercise Set 1: Renaming Columns

In [99]:
import pandas as pd

data = {
"fname": ["Alice", "Bob", "Charlie"],
"lname": ["Smith", "Jones", "Brown"],
"ctry": ["USA", "Canada", "UK"],
}

df = pd.DataFrame(data)

## Exercise 1

In [100]:
df.rename(columns={
    'fname': 'FirstName',
    'lname': 'LastName'
}, inplace=True)
print("1. Renamed 'fname' and 'lname':")
print(df)

1. Renamed 'fname' and 'lname':
  FirstName LastName    ctry
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

## Exercise 2

In [101]:
df.columns = ['FirstName', 'LastName', 'Country']
print("\n2. All column names changed:")
print(df)

2. All column names changed:
  FirstName LastName Country
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

## Exercise Set 2: Reordering Columns

In [102]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie"],
"Dept": ["HR", "Finance", "IT"],
"Sal": [60000, 70000, 80000],
}

df = pd.DataFrame(data)

## Exercise 1

In [103]:
df.rename(columns={
    'Dept': 'Department',
    'Sal': 'Salary'
}, inplace=True)
print("1. Renamed 'Dept' and 'Sal':")
print(df)

1. Renamed 'Dept' and 'Sal':
      Name Department  Salary
0    Alice         HR   60000
1      Bob    Finance   70000
2  Charlie         IT   80000

## Exercise 2

In [104]:
df = df[['Name', 'Department','Salary']]
cols = df.columns.tolist()
new_order = [cols[-1]] + cols[:-1]  
df = df[new_order]

## Exercise 3

In [105]:
print(df)

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT

## Exercise Set 3: GroupBy and Agg

In [106]:
import pandas as pd

data = {
"Store": ["A", "A", "A", "B", "B", "C", "C", "C", "C"],
"Product": ["Apples", "Oranges", "Bananas", "Apples", "Bananas", "Oranges", "Apples", "Bananas", "Bananas"],
"Sales": [100, 80, 90, 120, 110, 60, 95, 85, 75],
"Profit": [30, 25, 20, 40, 35, 15, 32, 22, 18],
}

df = pd.DataFrame(data)
print(df.head())

  Store  Product  Sales  Profit
0     A   Apples    100      30
1     A  Oranges     80      25
2     A  Bananas     90      20
3     B   Apples    120      40
4     B  Bananas    110      35

## Exercise 1

In [108]:
df.groupby('Store').agg({
    'Sales': 'mean',
    'Profit': 'mean'
})

        Sales  Profit
Store
A       90.00   25.00
B      115.00   37.50
C       78.75   21.75

## Exercise 2

In [109]:
df.groupby('Product').agg({
    'Sales': 'max',
    'Profit': 'min'
})

         Sales  Profit
Product
Apples     120      30
Bananas    110      18
Oranges     80      15

## Exercise 3

In [112]:
df.groupby('Store').agg(
    Avg_Sales=('Sales', 'mean'),
    Max_Profit=('Profit', 'max')
)

       Avg_Sales  Max_Profit
Store
A          90.00          30
B         115.00          40
C          78.75          32

## Exercise 4

In [113]:
df.groupby(['Store', 'Product']).agg({'Sales': 'sum'})

               Sales
Store Product
A     Apples     100
      Bananas     90
      Oranges     80
B     Apples     120
      Bananas    110
C     Apples      95
      Bananas    160
      Oranges     60

## Exercise Set 4: Joining

## Exercise 1

In [114]:
import pandas as pd

df_customers = pd.DataFrame({
"CustomerName": ["Alice", "Bob", "Charlie"]
}, index=[101, 102, 103])

df_orders = pd.DataFrame({
"OrderTotal": [250, 300, 400]
}, index=[101, 102, 103])

In [115]:
df_customers.join(df_orders, how='left')

    CustomerName  OrderTotal
101        Alice         250
102          Bob         300
103      Charlie         400

## Exercise 2

In [ ]:
df_cities = pd.DataFrame({
    'City': ['NYC', 'LA', 'Chicago']
}, index=[101, 102, 103])
print(df_customers.join(df_orders, how='left'))

    CustomerName     City
101        Alice      NYC
102          Bob       LA
103      Charlie  Chicago